config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :cars, only: %i[index show] do
    resources :reviews, only: %i[create]
    resources :favourites, only: [:create]
  end
  resources :favourites, only: %i[index destroy]

  get '/', to: 'pages#index'

  # get '/cars', to: 'cars#index'
  # get '/cars/:id', to: 'cars#show'
  # get '/cars/:id', to: 'cars#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner
  has_many :reviews
  has_many :favourites
  validates :brand, presence: true
  validates :model, presence: true
  validates :fuel, presence: true
  validates :year, presence: true, numericality: {
    only_integer: true,
    less_than_or_equal_to: Date.current.year,
    message: 'can not be in the future'
  }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_many :cars
  validates :nickname, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :comment, length: { minimum: 6 }, presence: true
  validates :rating, inclusion: { in: 0..5 }, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  def index
    @favourites = Favourite.all
  end

  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params[:id])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car

    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<%= render 'shared/navbar' %>

<div class="container w-50">
  <% @cars.each do |car| %>
    <div class="car-alone">
      <div class="car-detail">
        <h5><%= link_to car.brand , car_path(car) %></h5>
        <h6><%= car.model %></h6>
        <p><%= car.created_at.strftime("%a %b %e at %l:%M %p") %></p>
      </div>

      <%= image_tag(car.image_url || 'garage_banner.jpg', alt: "Car image") %>
      <%# <img src="https://images.pexels.com/photos/2664399/pexels-photo-2664399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" /> %>

      <div class="car-infos">
        <div>
          <%= link_to car_path(car) do %>
            <i class="fa-sharp fa-regular fa-comment"></i> <span>Comment</span>
          <% end %>
        </div>
        <div class="car-user">
          <span class="user-button"><%= car.owner.nickname %></span>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/cars/show.html.erb
<%= render 'shared/navbar' %>

<div class="container w-75 my-5">
  <div class="car-card">
    <%= image_tag(@car.image_url || 'garage_banner.jpg', alt: "Car image") %>
    <%# <img src="https://images.pexels.com/photos/2664399/pexels-photo-2664399.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" /> %>

    <div class="in-garage">
      <% if @car.favourites.empty? %>
        <%= simple_form_for [@car, @favourite] do |f| %>
          <%= f.submit "Save in my Garage", class: "btn btn-outline-secondary" %>
        <% end %>
      <% else %>
        <p>This is already in my Garage!</p>
      <% end %>
    </div>

    <div class="car-card-infos">
      <div>
        <h5 class="font-bold"><%= @car.brand %></h5>
        <h6 class="font-bold"><%= @car.model %></h6>
        <h6><%= @car.fuel %></h6>
        <h6><%= @car.year %></h6>
      </div>

      <div class="w-50">
        <%= simple_form_for [@car, @review] do |f| %>
          <%= f.input :comment, input_html: { placeholder: "Comment here.." } %>
          <%= f.input :rating, collection: 1..5 %>
          <div class="d-flex justify-content-end">
            <%= f.submit "Send", class: "btn btn-outline-secondary" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="review-section">
      <hr>
      <p>reviews (<%= @car.reviews.count %>):</p>
      <div>
        <% @car.reviews.each do |review| %>
          <p><%= review.comment %> <%= '⭐' * review.rating %></p>
        <% end %>
      </div>
      <hr>
    </div>
  </div>
</div>

app/views/favourites/index.html.erb
<%= render 'shared/navbar' %>

<div class="container w-50 my-5">
  <h4 class="garage-heading">My Garage</h4>

  <% @favourites.each do |favorite| %>
    <div class="garage-car">
      <%= image_tag(favorite.car.image_url || 'garage_banner.jpg', alt: "Car image") %>
      <%# <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" /> %>

      <div class="w-100 d-flex justify-content-between align-item-center">
        <div class="garage-car-infos">
          <h5><%= link_to favorite.car.brand, car_path(favorite.car) %></h5>
          <h6><%= favorite.car.model %></h6>
          <p><%= favorite.car.year %> | <%= favorite.car.fuel %></p>
        </div>

        <div class="garage-car-delete">
          <%= link_to favourite_path(favorite), data: { turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
            <i class="fa-sharp-duotone fa-regular fa-trash-can"></i>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= render 'shared/banner' %>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)), url('<%= image_path "garage_banner.jpg" %>')">
  <div>
    <h2>Awesome Garage</h2>
    <p>Your personal garage with the cars of your dreams</p>

    <%= link_to cars_path do %>
      <button type="button" class="btn btn-primary">Enter</button>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class= "navbar">
  <div>
    <%= link_to cars_path do %>
      <%= image_tag 'garage_logo.jpg' %>
      <span class="text-deco">Awesome Garage</span>
    <% end %>
  </div>

  <div>
    <%= link_to "Home", cars_path %>
    <%= link_to "My Garage", favourites_path %>
  </div>
</div>